export const products = [
  {
    id: 0,
    name: "Leather Jacket",
    category: "jackets",
    imgUrl: '/77e52966d5bd33267c4be54cc5c33a01.jpg',
    yOffset:'-10%',
    scale: 1,
    description:
      "Whether it's to protect from wind or just to look super cool, this leather jacket has you covered.",
    price: 7500,
  },
  {
    id: 1,
    name: "Wool Cardigan",
    category: "jackets",
    imgUrl: '/2270.webp',
    yOffset:'-25%',
    scale: 1,
    description:
      "Beautifully warm and soft, this cardigan will make you feel cosy on a cold day.",
    price: 8950,
  },
  {
    id: 2,
    name: "Striped Business Shirt",
    category: "shirts",
    imgUrl: '/FRANCISCO-GREEN-STRIPED-SHIRT-5_1800x1800.webp',
    yOffset:'-20%',
    scale: 0.75,
    description:
      "No ironing necessary to look professional every day with this striped shirt.",
    price: 900,
  },
  {
    id: 3,
    name: "Short-sleeved Polo Shirt",
    imgUrl: '/0fac8964f0a7a4078e32fb55e2f63d91.jpg',
    yOffset:'-5%',
    scale: 1,
    category: "shirts",
    description: "The best shirt you can get for that business-casual look.",
    price: 550,
  },
  {
    id: 4,
    name: "Plain Business Shirt",
    category: "shirts",
    imgUrl: '/WhiteTexturedPoplinOrlandoShirt_edited_1800x1800.webp',
    yOffset:'-10%',
    scale: 0.8,
    description:
      "No ironing necessary to look professional every day with this plain business shirt.",
    price: 1100,
  },
  {
    id: 5,
    name: "Suit Jacket",
    category: "jackets",
    imgUrl: '/thom-browne-spring-2020.jpg',
    yOffset:'-11%',
    scale: 0.8,
    description: "Wear it with jeans or suit pants, it works with both!",
    price: 12000,
  },
  {
    id: 6,
    name: "Suit Trousers",
    category: "pants",
    imgUrl: '/0pvs8ymazjb61.webp',
    yOffset:'-50%',
    scale: 1.2,
    description:
      "Get 5 of these and you've got pants for every day of the week.",
    price: 9000,
  },
  {
    id: 7,
    name: "Denim Jeans",
    category: "pants",
    imgUrl: '/Carmar_Extreme_Cut_Out_Jean_waitlist_2048x2048.webp',
    yOffset:'-40%',
    scale: 0.7,
    description:
      "A timeless classic, these denim jeans will never go out of style.",
    price: 11000,
  },
  {
    id: 8,
    name: "Pencil Skirt",
    category: "skirts",
    imgUrl: '/f16.webp',
    yOffset:'-20%',
    scale: 0.6,
    description:
      "A classy work-ready skirt that will make you feel like a million bucks.",
    price: 1000000,
  },
  {
    id: 9,
    name: "Cotton Flowy Skirt",
    category: "skirts",
    imgUrl: '/1951405.jpg',
    yOffset:'4%',
    scale: 1,
    description:
      "For those warm summer days when you just need to feel the breeze on your legs.",
    price: 45000,
  },
];